### PR TITLE
Feature/transactional db habitat deploy

### PR DESCRIPTION
**Pull request by akebi**
### Functionality Delivered in PR
* Habitat plan to build and install postgres
* INIT hook to create db superuser, setup PGDATA paths and initdb
* RUN hook to start postgres server daemon

### CODE REVIEW

**Comment by akebi** [comment]
@gitgik - all fixes applied for hab (native and container) deploy, ready for merge

**Comment by gitgik** [comment]
Looking good now! Just a simple readme documentation and it's ready

**Comment by akebi** [comment]
@jee, holding off on exposing the install from package in README until automated tests are included. that will be delivered through separate story

**Comment by gitgik** [comment]
LGTM 👍

**Pull request merged**
